import type { AppProps } from "next/app";
import Head from "next/head";

import "../styles/global.css";

import GlobalStyle from "../styles/globalStyles";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <GlobalStyle />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/fonts/avenir_ff/AvenirLTStd-Roman.otf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/avenir_ff/AvenirLTStd-Book.otf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/avenir_ff/AvenirLTStd-Black.otf"
          as="font"
          crossOrigin=""
        />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
export default MyApp;
