import type { AppProps } from "next/app";
import Head from "next/head";
import { Toaster } from "react-hot-toast";

import "../styles/global.css";

import GlobalStyle from "../styles/globalStyles";
import { StepProvider } from "../modules/order-card/custom-hooks/use-step";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <GlobalStyle />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap"
          rel="stylesheet"
        />
      </Head>
      <StepProvider>
        <Component {...pageProps} />
        <Toaster />
      </StepProvider>
    </>
  );
}
export default MyApp;
